"""empty message

Revision ID: 0568448c37c5
Revises: afda556267b3
Create Date: 2020-05-11 02:41:46.033226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0568448c37c5'
down_revision = 'afda556267b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Houses', sa.Column('agent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Houses', 'Agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Houses', type_='foreignkey')
    op.drop_column('Houses', 'agent_id')
    # ### end Alembic commands ###
