"""empty message

Revision ID: 32915b1b9be9
Revises: 0568448c37c5
Create Date: 2020-05-11 02:47:15.232392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32915b1b9be9'
down_revision = '0568448c37c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Houses', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Houses', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
